(require 'python)
(add-hook 'python-mode-hook (lambda ()
			      (require 'sphinx-doc)
			      (sphinx-doc-mode t)))
(add-hook 'python-mode-hook (lambda ()
			      (require 'ws-butler)
			      (ws-butler-mode)))
(unless (version< emacs-version "25")
  (add-hook 'python-mode-hook (lambda ()
                                (require 'fill-column-indicator)
                                (fci-mode)
                                (set-variable 'fci-rule-column 85))))

(cond ((equal company "arista")
       (add-hook 'python-mode-hook 'arastra-indent-python-mode-hook)))

